//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HandyKeras.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HandyKeras.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 HandyKeras 的本地化字符串。
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 即将呈现 的本地化字符串。
        /// </summary>
        public static string ComingSoon {
            get {
                return ResourceManager.GetString("ComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建空白项目 的本地化字符串。
        /// </summary>
        public static string CreateBlankProject {
            get {
                return ResourceManager.GetString("CreateBlankProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建不包含任何文件的空白项目 的本地化字符串。
        /// </summary>
        public static string CreateBlankProjectDetail {
            get {
                return ResourceManager.GetString("CreateBlankProjectDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建新项目 的本地化字符串。
        /// </summary>
        public static string CreateNewProject {
            get {
                return ResourceManager.GetString("CreateNewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择一份项目模板以开始 的本地化字符串。
        /// </summary>
        public static string CreateNewProjectDetail {
            get {
                return ResourceManager.GetString("CreateNewProjectDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 环境安装 的本地化字符串。
        /// </summary>
        public static string EnvInstall {
            get {
                return ResourceManager.GetString("EnvInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始安装;无需安装 的本地化字符串。
        /// </summary>
        public static string EnvStatusStr {
            get {
                return ResourceManager.GetString("EnvStatusStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请稍后，正在下载Keras环境 的本地化字符串。
        /// </summary>
        public static string KerasDownloadWaitOn {
            get {
                return ResourceManager.GetString("KerasDownloadWaitOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线性回归 的本地化字符串。
        /// </summary>
        public static string LinearRegression {
            get {
                return ResourceManager.GetString("LinearRegression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MNIST 手写数字 的本地化字符串。
        /// </summary>
        public static string Mnist {
            get {
                return ResourceManager.GetString("Mnist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MNIST 手写数字（卷积） 的本地化字符串。
        /// </summary>
        public static string MnistConv {
            get {
                return ResourceManager.GetString("MnistConv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开本地项目 的本地化字符串。
        /// </summary>
        public static string OpenLocalProject {
            get {
                return ResourceManager.GetString("OpenLocalProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开本地HandyKeras项目 的本地化字符串。
        /// </summary>
        public static string OpenLocalProjectDetail {
            get {
                return ResourceManager.GetString("OpenLocalProjectDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开最近项 的本地化字符串。
        /// </summary>
        public static string OpenRecentlyProject {
            get {
                return ResourceManager.GetString("OpenRecentlyProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始安装 的本地化字符串。
        /// </summary>
        public static string StartInstallation {
            get {
                return ResourceManager.GetString("StartInstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择项目开始的方式 的本地化字符串。
        /// </summary>
        public static string StartProject {
            get {
                return ResourceManager.GetString("StartProject", resourceCulture);
            }
        }
    }
}
